language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - composer install --ignore-platform-reqs
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:load --env=test
    - bin/console fixture:load --env=test

branches:
  only:
    - master
